import { StationLinks } from "../types/stationLinks"


    export const stationLinks:StationLinks[] = [
        {
            fromCode:1,
            to:[
                {
                    toCode:2,
                    lineType:'blue'
                },
                {
                    toCode:273,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:2,
            to:[
                {
                    toCode:1,
                    lineType:'blue'
                },
                {
                    toCode:3,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:3,
            to:[
                {
                    toCode:2,
                    lineType:'blue'
                },
                {
                    toCode:4,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:4,
            to:[
                {
                    toCode:3,
                    lineType:'blue'
                },
                {
                    toCode:5,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:5,
            to:[
                {
                    toCode:4,
                    lineType:'blue'
                },
                {
                    toCode:6,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:6,
            to:[
                {
                    toCode:7,
                    lineType:'blue'
                },
                {
                    toCode:5,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:7,
            to:[
                {
                    toCode:6,
                    lineType:'blue'
                },
                {
                    toCode:8,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:8,
            to:[
                {
                    toCode:7,
                    lineType:'blue'
                },
                {
                    toCode:9,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:9,
            to:[
                {
                    toCode:8,
                    lineType:'blue'
                },
                {
                    toCode:10,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:10,
            to:[
                {
                    toCode:9,
                    lineType:'blue'
                },
                {
                    toCode:11,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:11,
            to:[
                {
                    toCode:12,
                    lineType:'blue'
                },
                {
                    toCode:10,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:12,
            to:[
                {
                    toCode:11,
                    lineType:'blue'
                },
                {
                    toCode:13,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:13,
            to:[
                {
                    toCode:12,
                    lineType:'blue'
                },
                {
                    toCode:14,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:14,
            to:[
                {
                    toCode:13,
                    lineType:'blue'
                },
                {
                    toCode:15,
                    lineType:'blue'
                },
                {
                    toCode:184,
                    lineType:'magenta'
                },
                {
                    toCode:183,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:15,
            to:[
                {
                    toCode:14,
                    lineType:'blue'
                },
                {
                    toCode:16,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:16,
            to:[
                {
                    toCode:15,
                    lineType:'blue'
                },
                {
                    toCode:17,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:17,
            to:[
                {
                    toCode:16,
                    lineType:'blue'
                },
                {
                    toCode:18,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:18,
            to:[
                {
                    toCode:17,
                    lineType:'blue'
                },
                {
                    toCode:19,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:19,
            to:[
                {
                    toCode:18,
                    lineType:'blue'
                },
                {
                    toCode:20,
                    lineType:'blue'
                },
                {
                    toCode:229,
                    lineType:'pink'
                },
                {
                    toCode:230,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:20,
            to:[
                {
                    toCode:19,
                    lineType:'blue'
                },
                {
                    toCode:21,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:21,
            to:[
                {
                    toCode:20,
                    lineType:'blue'
                },
                {
                    toCode:22,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:22,
            to:[
                {
                    toCode:21,
                    lineType:'blue'
                },
                {
                    toCode:23,
                    lineType:'blue'
                },
                {
                    toCode:113,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:23,
            to:[
                {
                    toCode:22,
                    lineType:'blue'
                },
                {
                    toCode:24,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:24,
            to:[
                {
                    toCode:23,
                    lineType:'blue'
                },
                {
                    toCode:25,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:25,
            to:[
                {
                    toCode:24,
                    lineType:'blue'
                },
                {
                    toCode:26,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:26,
            to:[
                {
                    toCode:25,
                    lineType:'blue'
                },
                {
                    toCode:27,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:27,
            to:[
                {
                    toCode:26,
                    lineType:'blue'
                },
                {
                    toCode:28,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:28,
            to:[
                {
                    toCode:27,
                    lineType:'blue'
                },
                {
                    toCode:29,
                    lineType:'blue'
                },
                {
                    toCode:118,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:29,
            to:[
                {
                    toCode:28,
                    lineType:'blue'
                },
                {
                    toCode:30,
                    lineType:'blue'
                },
                {
                    toCode:73,
                    lineType:'yellow'
                },
                {
                    toCode:72,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:30,
            to:[
                {
                    toCode:29,
                    lineType:'blue'
                },
                {
                    toCode:31,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:31,
            to:[
                {
                    toCode:30,
                    lineType:'blue'
                },
                {
                    toCode:32,
                    lineType:'blue'
                },
                {
                    toCode:243,
                    lineType:'violet'
                },
                {
                    toCode:244,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:32,
            to:[
                {
                    toCode:31,
                    lineType:'blue'
                },
                {
                    toCode:33,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:33,
            to:[
                {
                    toCode:32,
                    lineType:'blue'
                },
                {
                    toCode:34,
                    lineType:'blue'
                },
                {
                    toCode:121,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:34,
            to:[
                {
                    toCode:33,
                    lineType:'blue'
                },
                {
                    toCode:35,
                    lineType:'blue'
                },
                {
                    toCode:42,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:35,
            to:[
                {
                    toCode:34,
                    lineType:'blue'
                },
                {
                    toCode:36,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:36,
            to:[
                {
                    toCode:35,
                    lineType:'blue'
                },
                {
                    toCode:37,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:37,
            to:[
                {
                    toCode:36,
                    lineType:'blue'
                },
                {
                    toCode:38,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:38,
            to:[
                {
                    toCode:37,
                    lineType:'blue'
                },
                {
                    toCode:39,
                    lineType:'blue'
                },
                {
                    toCode:39,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:39,
            to:[
                {
                    toCode:38,
                    lineType:'blue'
                },
                {
                    toCode:40,
                    lineType:'blue'
                },
                {
                    toCode:38,
                    lineType:'pink'
                },
                {
                    toCode:214,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:40,
            to:[
                {
                    toCode:39,
                    lineType:'blue'
                },
                {
                    toCode:41,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:41,
            to:[
                {
                    toCode:40,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:42,
            to:[
                {
                    toCode:34,
                    lineType:'blue'
                },
                {
                    toCode:43,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:43,
            to:[
                {
                    toCode:42,
                    lineType:'blue'
                },
                {
                    toCode:219,
                    lineType:'pink'
                },
                {
                    toCode:218,
                    lineType:'pibk'
                },
                {
                    toCode:44,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:44,
            to:[
                {
                    toCode:43,
                    lineType:'blue'
                },
                {
                    toCode:45,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:45,
            to:[
                {
                    toCode:44,
                    lineType:'blue'
                },
                {
                    toCode:46,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:46,
            to:[
                {
                    toCode:45,
                    lineType:'blue'
                },
                {
                    toCode:47,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:47,
            to:[
                {
                    toCode:46,
                    lineType:'blue'
                },{
                    toCode:48,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:48,
            to:[
                {
                    toCode:47,
                    lineType:'blue'
                },
                {
                    toCode:49,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:49,
            to:[
                {
                    toCode:48,
                    lineType:'blue'
                },
                {
                    toCode:205,
                    lineType:'magenta'
                },
                {
                    toCode:50,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:50,
            to:[
                {
                    toCode:49,
                    lineType:'blue'
                },
                {
                    toCode:51,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:51,
            to:[
                {
                    toCode:50,
                    lineType:'blue'
                },
                {
                    toCode:52,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:52,
            to:[
                {
                    toCode:51,
                    lineType:'blue'
                },
                {
                    toCode:53,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:53,
            to:[
                {
                    toCode:52,
                    lineType:'blue'
                },
                {
                    toCode:54,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:54,
            to:[
                {
                    toCode:53,
                    lineType:'blue'
                },
                {
                    toCode:55,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:55,
            to:[
                {
                    toCode:54,
                    lineType:'blue'
                },
                {
                    toCode:56,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:56,
            to:[
                {
                    toCode:55,
                    lineType:'blue'
                },
                {
                    toCode:57,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:57,
            to:[
                {
                    toCode:56,
                    lineType:'blue'
                }
            ]
        },
        {
            fromCode:58,
            to:[
                {
                    toCode:59,
                    lineType:'yellow '
                }
            ]
        },
        {
            fromCode:59,
            to:[
                {
                    toCode:58,
                    lineType:'yellow'
                },
                {
                    toCode:60,
                    lineType:'yellow'
                }

            ]
        },
        {
            fromCode:60,
            to:[
                {
                    toCode:59,
                    lineType:'yellow'
                },
                {
                    toCode:61,
                    lineType:'yellow'
                },
                {
                    toCode:173,
                    lineType:'magenta'
                },{
                    toCode:174,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:61,
            to:[
                {
                    toCode:60,
                    lineType:'yellow'
                },
                {
                    toCode:62,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:62,
            to:[
                {
                    toCode:61,
                    lineType:'yellow'
                },
                {
                    toCode:63,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:63,
            to:[
                {
                    toCode:62,
                    lineType:'yellow'
                },
                {
                    toCode:64,
                    lineType:'yellow'
                },
                {
                    toCode:233,
                    lineType:'pink'
                },
                {
                    toCode:172,
                    lineType:'pink'
                },
                {
                    toCode:172,
                    lineType:'magenta'
                },{
                    toCode:171,
                    lineType:'magenta'
                }
                
            ]
        },
        {
            fromCode:64,
            to:[
                {
                    toCode:63,
                    lineType:'yellow'
                },
                {
                    toCode:65,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:65,
            to:[
                {
                    toCode:64,
                    lineType:'yellow'
                },
                {
                    toCode:66,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:66,
            to:[
                {
                    toCode:65,
                    lineType:'yellow'
                },
                {
                    toCode:67,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:67,
            to:[
                {
                    toCode:66,
                    lineType:'yellow'
                },
                {
                    toCode:68,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:68,
            to:[
                {
                    toCode:67,
                    lineType:'yellow'
                },
                {
                    toCode:69,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:69,
            to:[
                {
                    toCode:68,
                    lineType:'yellow'
                },
                {
                    toCode:70,
                    lineType:'yellow'
                },
                {
                    toCode:152,
                    lineType:'red'
                },
                {
                    toCode:153,
                    lineType:'red'
                },
                {
                    toCode:241,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:70,
            to:[
                {
                    toCode:69,
                    lineType:'yellow'
                },
                {
                    toCode:71,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:71,
            to:[
                {
                    toCode:70,
                    lineType:'yellow'
                },
                {
                    toCode:72,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:72,
            to:[
                {
                    toCode:71,
                    lineType:'yellow'
                },
                {
                    toCode:29,
                    lineType:'yellow'
                },
                {
                    toCode:118,
                    lineType:'green'
                },
                {
                    toCode:119,
                    lineType:'green'
                },
                {
                    toCode:277,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:73,
            to:[
                {
                    toCode:29,
                    lineType:'yellow'
                },
                {
                    toCode:245,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:74,
            to:[
                {
                    toCode:245,
                    lineType:'yellow'
                },
                {
                    toCode:75,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:75,
            to:[
                {
                    toCode:74,
                    lineType:'yellow'
                },
                {
                    toCode:59,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:76,
            to:[
                {
                    toCode:75,
                    lineType:'yellow'
                },
                {
                    toCode:77,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:77,
            to:[
                {
                    toCode:76,
                    lineType:'yellow'
                },
                {
                    toCode:78,
                    lineType:'yellow'
                },
                {
                    toCode:223,
                    lineType:'pink'
                },
                {
                    toCode:234,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:78,
            to:[
                {
                    toCode:77,
                    lineType:'yellow'
                },
                {
                    toCode:79,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:79,
            to:[
                {
                    toCode:78,
                    lineType:'yellow'
                },
                {
                    toCode:80,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:80,
            to:[
                {
                    toCode:79,
                    lineType:'yellow'
                },
                {
                    toCode:81,
                    lineType:'yellow'
                },
                {
                    toCode:193,
                    lineType:'magenta'
                },
                {
                    toCode:194,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:81,
            to:[
                {
                    toCode:80,
                    lineType:'yellow'
                },
                {
                    toCode:82,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:82,
            to:[
                {
                    toCode:81,
                    lineType:'yellow'
                },
                {
                    toCode:83,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:83,
            to:[
                {
                    toCode:82,
                    lineType:'yellow'
                },
                {
                    toCode:84,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:84,
            to:[
                {
                    toCode:83,
                    lineType:'yellow'
                },
                {
                    toCode:85,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:85,
            to:[
                {
                    toCode:84,
                    lineType:'yellow'
                },
                {
                    toCode:86,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:86,
            to:[
                {
                    toCode:85,
                    lineType:'yellow'
                },
                {
                    toCode:87,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:87,
            to:[
                {
                    toCode:86,
                    lineType:'yellow'
                },
                {
                    toCode:88,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:88,
            to:[
                {
                    toCode:87,
                    lineType:'yellow'
                },
                {
                    toCode:89,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:89,
            to:[
                {
                    toCode:88,
                    lineType:'yellow'
                },
                {
                    toCode:90,
                    lineType:'yellow'
                },
                {
                    toCode:304,
                    lineType:'rapid'
                },
                {
                    toCode:303,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:90,
            to:[
                {
                    toCode:89,
                    lineType:'yellow'
                },
                {
                    toCode:91,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:91,
            to:[
                {
                    toCode:90,
                    lineType:'yellow'
                },
                {
                    toCode:92,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:92,
            to:[
                {
                    toCode:91,
                    lineType:'yellow'
                }
            ]
        },
        {
            fromCode:93,
            to:[
                {
                    toCode:94,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:94,
            to:[
                {
                    toCode:93,
                    lineType:'green'
                },
                {
                    toCode:95,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:95,
            to:[
                {
                    toCode:94,
                    lineType:'green'
                },
                {
                    toCode:96,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:96,
            to:[
                {
                    toCode:95,
                    lineType:'green'
                },
                {
                    toCode:97,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:97,
            to:[
                {
                    toCode:96,
                    lineType:'green'
                },
                {
                    toCode:98,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:98,
            to:[
                {
                    toCode:97,
                    lineType:'green'
                },
                {
                    toCode:99,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:99,
            to:[
                {
                    toCode:98,
                    lineType:'green'
                },
                {
                    toCode:100,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:100,
            to:[
                {
                    toCode:99,
                    lineType:'green'
                },
                {
                    toCode:101,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:101,
            to:[
                {
                    toCode:102,
                    lineType:'green'
                },
                {
                    toCode:100,
                    lineType:'green'
                },
                
            ]
        },
        {
            fromCode:102,
            to:[
                {
                    toCode:101,
                    lineType:'green'
                },
                {
                    toCode:103,
                    lineType:'green'
                },
            ]
        },
        {
            fromCode:103,
            to:[
                {
                    toCode:102,
                    lineType:'green'
                },
                {
                    toCode:104,
                    lineType:'green'
                },
            ]
        },
        {
            fromCode:104,
            to:[
                {
                    toCode:103,
                    lineType:'green'
                },
                {
                    toCode:105,
                    lineType:'green'
                },
            ]
        },
        {
            fromCode:105,
            to:[
                {
                    toCode:104,
                    lineType:'green'
                },
                {
                    toCode:106,
                    lineType:'green'
                },
            ]
        },
        {
            fromCode:106,
            to:[
                {
                    toCode:105,
                    lineType:'green'
                },
                {
                    toCode:107,
                    lineType:'green'
                },
                {
                    toCode:180,
                    lineType:'magenta'
                },
                {
                    toCode:181,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:107,
            to:[
                {
                    toCode:106,
                    lineType:'green'
                },
                {
                    toCode:108,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:108,
            to:[
                {
                    toCode:107,
                    lineType:'green'
                },
                {
                    toCode:109,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:109,
            to:[
                {
                    toCode:108,
                    lineType:'green'
                },
                {
                    toCode:110,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:110,
            to:[
                {
                    toCode:109,
                    lineType:'green'
                },
                {
                    toCode:111,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:111,
            to:[
                {
                    toCode:110,
                    lineType:'green'
                },
                {
                    toCode:112,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:112,
            to:[
                {
                    toCode:111,
                    lineType:'green'
                },
                {
                    toCode:114,
                    lineType:'green'
                },
                {
                    toCode:113,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:113,
            to:[
                {
                    toCode:112,
                    lineType:'green'
                },
                {
                    toCode:22,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:114,
            to:[
                {
                    toCode:113,
                    lineType:'green'
                },
                {
                    toCode:115,
                    lineType:'green'
                },
                {
                    toCode:149,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:115,
            to:[
                {
                    toCode:114,
                    lineType:'green'
                },
                {
                    toCode:116,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:116,
            to:[
                {
                    toCode:115,
                    lineType:'green'
                },
                {
                    toCode:117,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:117,
            to:[
                {
                    toCode:116,
                    lineType:'green'
                },
                {
                    toCode:118,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:118,
            to:[
                {
                    toCode:117,
                    lineType:'green'
                },
                {
                    toCode:72,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:119,
            to:[
                {
                    toCode:120,
                    lineType:'green'
                },
                {
                    toCode:72,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:120,
            to:[
                {
                    toCode:119,
                    lineType:'yellow'
                },
                {
                    toCode:121,
                    lineType:'green'
                },
                {
                    toCode:243,
                    lineType:'violet'
                },
                {
                    toCode:242,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:121,
            to:[
                {
                    toCode:120,
                    lineType:'yellow'
                },
                {
                    toCode:33,
                    lineType:'green'
                }
            ]
        },
        {
            fromCode:122,
            to:[
                {
                    toCode:123,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:123,
            to:[
                {
                    toCode:122,
                    lineType:'red'
                },
                {
                    toCode:124,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:124,
            to:[
                {
                    toCode:123,
                    lineType:'red'
                },
                {
                    toCode:125,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:125,
            to:[
                {
                    toCode:124,
                    lineType:'red'
                },
                {
                    toCode:127,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:126,
            to:[
                {
                    toCode:127,
                    lineType:'red'
                },
                {
                    toCode:128,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:127,
            to:[
                {
                    toCode:125,
                    lineType:'red'
                },
                {
                    toCode:126,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:128,
            to:[
                {
                    toCode:126,
                    lineType:'red'
                },
                {
                    toCode:129,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:129,
            to:[
                {
                    toCode:128,
                    lineType:'red'
                },
                {
                    toCode:130,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:130,
            to:[
                {
                    toCode:129,
                    lineType:'red'
                },
                {
                    toCode:131,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:131,
            to:[
                {
                    toCode:130,
                    lineType:'red'
                },
                {
                    toCode:132,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:132,
            to:[
                {
                    toCode:131,
                    lineType:'red'
                },
                {
                    toCode:133,
                    lineType:'red'
                }

            ]
        },
        {
            fromCode:133,
            to:[
                {
                    toCode:132,
                    lineType:'red'
                },
                {
                    toCode:134,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:134,
            to:[
                {
                    toCode:133,
                    lineType:'red'
                },
                {
                    toCode:135,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:135,
            to:[
                {
                    toCode:134,
                    lineType:'red'
                },
                {
                    toCode:136,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:136,
            to:[
                {
                    toCode:135,
                    lineType:'red'
                },
                {
                    toCode:137,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:137,
            to:[
                {
                    toCode:136,
                    lineType:'red'
                },
                {
                    toCode:138,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:138,
            to:[
                {
                    toCode:137,
                    lineType:'red'
                },
                {
                    toCode:139,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:139,
            to:[
                {
                    toCode:138,
                    lineType:'red'
                },
                {
                    toCode:140,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:140,
            to:[
                {
                    toCode:139,
                    lineType:'red'
                },
                {
                    toCode:141,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:141,
            to:[
                {
                    toCode:140,
                    lineType:'red'
                },
                {
                    toCode:142,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:142,
            to:[
                {
                    toCode:141,
                    lineType:'red'
                },
                {
                    toCode:143,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:143,
            to:[
                {
                    toCode:142,
                    lineType:'red'
                },
                {
                    toCode:144,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:144,
            to:[
                {
                    toCode:143,
                    lineType:'red'
                },
                {
                    toCode:145,
                    lineType:'red'
                },
                {
                    toCode:176,
                    lineType:'magenta'
                },
                {
                    toCode:175,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:145,
            to:[
                {
                    toCode:144,
                    lineType:'red'
                },
                {
                    toCode:146,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:146,
            to:[
                {
                    toCode:145,
                    lineType:'red'
                },
                {
                    toCode:147,
                    lineType:'red'
                },
                {
                    toCode:232,
                    lineType:'pink'
                },
                {
                    toCode:233,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:147,
            to:[
                {
                    toCode:146,
                    lineType:'red'
                },
                {
                    toCode:148,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:148,
            to:[
                {
                    toCode:147,
                    lineType:'red'
                },
                {
                    toCode:114,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:149,
            to:[
                {
                    toCode:114,
                    lineType:'red'
                },
                {
                    toCode:150,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:150,
            to:[
                {
                    toCode:149,
                    lineType:'red'
                },
                {
                    toCode:151,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:151,
            to:[
                {
                    toCode:150,
                    lineType:'red'
                },
                {
                    toCode:152,
                    lineType:'red'
                },
                {
                    toCode:169,
                    lineType:'magenta'
                },
                {
                    toCode:168,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:152,
            to:[
                {
                    toCode:151,
                    lineType:'red'
                },
                {
                    toCode:69,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:153,
            to:[
                {
                    toCode:69,
                    lineType:'red'
                },
                {
                    toCode:154,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:154,
            to:[
                {
                    toCode:153,
                    lineType:'red'
                },
                {
                    toCode:155,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:155,
            to:[
                {
                    toCode:154,
                    lineType:'red'
                },
                {
                    toCode:156,
                    lineType:'red'
                },
                {
                    toCode:210,
                    lineType:'pink'
                },
                {
                    toCode:211,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:156,
            to:[
                {
                    toCode:155,
                    lineType:'red'
                },
                {
                    toCode:157,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:157,
            to:[
                {
                    toCode:156,
                    lineType:'red'
                },
                {
                    toCode:158,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:158,
            to:[
                {
                    toCode:157,
                    lineType:'red'
                },
                {
                    toCode:159,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:159,
            to:[
                {
                    toCode:158,
                    lineType:'red'
                },
                {
                    toCode:160,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:160,
            to:[
                {
                    toCode:159,
                    lineType:'red'
                },
                {
                    toCode:161,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:161,
            to:[
                {
                    toCode:160,
                    lineType:'red'
                },
                {
                    toCode:162,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:162,
            to:[
                {
                    toCode:161,
                    lineType:'red'
                },
                {
                    toCode:163,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:163,
            to:[
                {
                    toCode:162,
                    lineType:'red'
                },
                {
                    toCode:164,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:164,
            to:[
                {
                    toCode:163,
                    lineType:'red'
                },
                {
                    toCode:165,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:165,
            to:[
                {
                    toCode:164,
                    lineType:'red'
                },
                {
                    toCode:166,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:166,
            to:[
                {
                    toCode:165,
                    lineType:'red'
                },
                {
                    toCode:167,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:167,
            to:[
                {
                    toCode:166,
                    lineType:'red'
                }
            ]
        },
        {
            fromCode:168,
            to:[
                {
                    toCode:118,
                    lineType:'magenta'
                },
                {
                    toCode:151,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:169,
            to:[
                {
                    toCode:151,
                    lineType:'magenta'
                },
                {
                    toCode:170,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:170,
            to:[
                {
                    toCode:169,
                    lineType:'magenta'
                },
                {
                    toCode:171,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:171,
            to:[
                {
                    toCode:170,
                    lineType:'magenta'
                },
                {
                    toCode:63,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:172,
            to:[
                {
                    toCode:63,
                    lineType:'magenta'
                },
                {
                    toCode:63,
                    lineType:'pink'
                },
                {
                    toCode:234,
                    lineType:'pink'
                },
                {
                    toCode:173,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:173,
            to:[
                {
                    toCode:172,
                    lineType:'magenta'
                },
                {
                    toCode:60,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:174,
            to:[
                {
                    toCode:60,
                    lineType:'magenta'
                },
                {
                    toCode:175,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:175,
            to:[
                {
                    toCode:174,
                    lineType:'magenta'
                },
                {
                    toCode:144,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:176,
            to:[
                {
                    toCode:144,
                    lineType:'magenta'
                },
                {
                    toCode:177,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:177,
            to:[
                {
                    toCode:176,
                    lineType:'magenta'
                },
                {
                    toCode:178,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:178,
            to:[
                {
                    toCode:177,
                    lineType:'magenta'
                },
                {
                    toCode:179,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:179,
            to:[
                {
                    toCode:178,
                    lineType:'magenta'
                },
                {
                    toCode:180,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:180,
            to:[
                {
                    toCode:179,
                    lineType:'magenta'
                },
                {
                    toCode:106,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:181,
            to:[
                {
                    toCode:106,
                    lineType:'magenta'
                },
                {
                    toCode:182,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:182,
            to:[
                {
                    toCode:181,
                    lineType:'magenta'
                },
                {
                    toCode:183,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:183,
            to:[
                {
                    toCode:182,
                    lineType:'magenta'
                },
                {
                    toCode:14,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:184,
            to:[
                {
                    toCode:14,
                    lineType:'magenta'
                },
                {
                    toCode:185,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:185,
            to:[
                {
                    toCode:184,
                    lineType:'magenta'
                },
                {
                    toCode:186,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:186,
            to:[
                {
                    toCode:185,
                    lineType:'magenta'
                },
                {
                    toCode:187,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:187,
            to:[
                {
                    toCode:186,
                    lineType:'magenta'
                },
                {
                    toCode:188,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:188,
            to:[
                {
                    toCode:187,
                    lineType:'magenta'
                },
                {
                    toCode:189,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:189,
            to:[
                {
                    toCode:188,
                    lineType:'magenta'
                },
                {
                    toCode:190,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:190,
            to:[
                {
                    toCode:189,
                    lineType:'magenta'
                },
                {
                    toCode:191,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:191,
            to:[
                {
                    toCode:190,
                    lineType:'magenta'
                },
                {
                    toCode:192,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:192,
            to:[
                {
                    toCode:191,
                    lineType:'magenta'
                },
                {
                    toCode:193,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:193,
            to:[
                {
                    toCode:192,
                    lineType:'magenta'
                },
                {
                    toCode:80,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:194,
            to:[
                {
                    toCode:80,
                    lineType:'magenta'
                },
                {
                    toCode:195,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:195,
            to:[
                {
                    toCode:194,
                    lineType:'magenta'
                },
                {
                    toCode:196,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:196,
            to:[
                {
                    toCode:195,
                    lineType:'magenta'
                },
                {
                    toCode:197,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:197,
            to:[
                {
                    toCode:196,
                    lineType:'magenta'
                },
                {
                    toCode:198,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:198,
            to:[
                {
                    toCode:197,
                    lineType:'magenta'
                },
                {
                    toCode:252,
                    lineType:'violet'
                },
                {
                    toCode:251,
                    lineType:'violet'
                },
                {
                    toCode:199,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:199,
            to:[
                {
                    toCode:198,
                    lineType:'magenta'
                },
                {
                    toCode:200,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:200,
            to:[
                {
                    toCode:199,
                    lineType:'magenta'
                },
                {
                    toCode:201,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:201,
            to:[
                {
                    toCode:200,
                    lineType:'magenta'
                },
                {
                    toCode:202,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:202,
            to:[
                {
                    toCode:201,
                    lineType:'magenta'
                },
                {
                    toCode:203,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:203,
            to:[
                {
                    toCode:202,
                    lineType:'magenta'
                },
                {
                    toCode:204,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:204,
            to:[
                {
                    toCode:203,
                    lineType:'magenta'
                },
                {
                    toCode:205,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:205,
            to:[
                {
                    toCode:204,
                    lineType:'magenta'
                },
                {
                    toCode:49,
                    lineType:'magenta'
                }
            ]
        },
        {
            fromCode:206,
            to:[
                {
                    toCode:207,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:207,
            to:[
                {
                    toCode:206,
                    lineType:'pink'
                },
                {
                    toCode:208,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:208,
            to:[
                {
                    toCode:207,
                    lineType:'pink'
                },
                {
                    toCode:209,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:209,
            to:[
                {
                    toCode:208,
                    lineType:'pink'
                },
                {
                    toCode:240,
                    lineType:'pink'
                },
                {
                    toCode:120,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:210,
            to:[
                {
                    toCode:209,
                    lineType:'pink'
                },
                {
                    toCode:155,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:211,
            to:[
                {
                    toCode:155,
                    lineType:'pink'
                },
                {
                    toCode:212,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:212,
            to:[
                {
                    toCode:211,
                    lineType:'pink'
                },
                {
                    toCode:213,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:213,
            to:[
                {
                    toCode:212,
                    lineType:'pink'
                },
                {
                    toCode:38,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:214,
            to:[
                {
                    toCode:39,
                    lineType:'pink'
                },
                {
                    toCode:215,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:215,
            to:[
                {
                    toCode:214,
                    lineType:'pink'
                },
                {
                    toCode:216,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:216,
            to:[
                {
                    toCode:215,
                    lineType:'pink'
                },
                {
                    toCode:217,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:217,
            to:[
                {
                    toCode:216,
                    lineType:'pink'
                },
                {
                    toCode:218,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:218,
            to:[
                {
                    toCode:217,
                    lineType:'pink'
                },
                {
                    toCode:43,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:219,
            to:[
                {
                    toCode:43,
                    lineType:'pink'
                },
                {
                    toCode:220,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:220,
            to:[
                {
                    toCode:219,
                    lineType:'pink'
                },
                {
                    toCode:221,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:221,
            to:[
                {
                    toCode:220,
                    lineType:'pink'
                },
                {
                    toCode:222,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:222,
            to:[
                {
                    toCode:221,
                    lineType:'pink'
                },
                {
                    toCode:223,
                    lineType:'pink'
                },
                {
                    toCode:248,
                    lineType:'violet'
                },
                {
                    toCode:249,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:223,
            to:[
                {
                    toCode:222,
                    lineType:'pink'
                },
                {
                    toCode:77,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:224,
            to:[
                {
                    toCode:77,
                    lineType:'pink'
                },
                {
                    toCode:225,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:225,
            to:[
                {
                    toCode:224,
                    lineType:'pink'
                },
                {
                    toCode:226,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:226,
            to:[
                {
                    toCode:225,
                    lineType:'pink'
                },
                {
                    toCode:276,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:227,
            to:[
                {
                    toCode:276,
                    lineType:'pink'
                },
                {
                    toCode:228,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:228,
            to:[
                {
                    toCode:227,
                    lineType:'pink'
                },
                {
                    toCode:229,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:229,
            to:[
                {
                    toCode:228,
                    lineType:'pink'
                },
                {
                    toCode:19,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:230,
            to:[
                {
                    toCode:19,
                    lineType:'pink'
                },
                {
                    toCode:231,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:231,
            to:[
                {
                    toCode:230,
                    lineType:'pink'
                },
                {
                    toCode:232,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:232,
            to:[
                {
                    toCode:231,
                    lineType:'pink'
                },
                {
                    toCode:146,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:233,
            to:[
                {
                    toCode:146,
                    lineType:'pink'
                },
                {
                    toCode:63,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:234,
            to:[
                {
                    toCode:172,
                    lineType:'pink'
                },
                {
                    toCode:235,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:235,
            to:[
                {
                    toCode:234,
                    lineType:'pink'
                },
                {
                    toCode:236,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:236,
            to:[
                {
                    toCode:235,
                    lineType:'pink'
                },
                {
                    toCode:309,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:237,
            to:[
                {
                    toCode:309,
                    lineType:'pink'
                },
                {
                    toCode:238,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:238,
            to:[
                {
                    toCode:2,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:239,
            to:[
                {
                    toCode:238,
                    lineType:'pink'
                },
                {
                    toCode:240,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:240,
            to:[
                {
                    toCode:239,
                    lineType:'pink'
                },
                {
                    toCode:209,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:241,
            to:[
                {
                    toCode:242,
                    lineType:'violet'
                },
                {
                    toCode:69,
                    lineType:'violet'
                }

            ]
        },
        {
            fromCode:242,
            to:[
                {
                    toCode:241,
                    lineType:'violet'
                },
                {
                    toCode:120,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:243,
            to:[
                {
                    toCode:120,
                    lineType:'violet'
                },
                {
                    toCode:31,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:244,
            to:[
                {
                    toCode:31,
                    lineType:'violet'
                },
                {
                    toCode:245,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:245,
            to:[
                {
                    toCode:73,
                    lineType:'yellow'
                },
                {
                    toCode:74,
                    lineType:'yellow'
                },
                {
                    toCode:244,
                    lineType:'violet'
                },
                {
                    toCode:246,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:246,
            to:[
                {
                    toCode:245,
                    lineType:'violet'
                },
                {
                    toCode:247,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:247,
            to:[
                {
                    toCode:246,
                    lineType:'violet'
                },
                {
                    toCode:248,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:248,
            to:[
                {
                    toCode:247,
                    lineType:'violet'
                },
                {
                    toCode:222,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:249,
            to:[
                {
                    toCode:222,
                    lineType:'violet'
                },
                {
                    toCode:250,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:250,
            to:[
                {
                    toCode:249,
                    lineType:'violet'
                },
                {
                    toCode:251,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:251,
            to:[
                {
                    toCode:250,
                    lineType:'violet'
                },
                {
                    toCode:198,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:252,
            to:[
                {
                    toCode:198,
                    lineType:'violet'
                },
                {
                    toCode:253,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:253,
            to:[
                {
                    toCode:252,
                    lineType:'violet'
                },
                {
                    toCode:254,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:254,
            to:[
                {
                    toCode:253,
                    lineType:'violet'
                },
                {
                    toCode:255,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:255,
            to:[
                {
                    toCode:254,
                    lineType:'violet'
                },
                {
                    toCode:256,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:256,
            to:[
                {
                    toCode:255,
                    lineType:'violet'
                },
                {
                    toCode:257,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:257,
            to:[
                {
                    toCode:256,
                    lineType:'violet'
                },
                {
                    toCode:258,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:258,
            to:[
                {
                    toCode:257,
                    lineType:'violet'
                },
                {
                    toCode:259,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:259,
            to:[
                {
                    toCode:258,
                    lineType:'violet'
                },
                {
                    toCode:260,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:260,
            to:[
                {
                    toCode:259,
                    lineType:'violet'
                },
                {
                    toCode:261,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:261,
            to:[
                {
                    toCode:260,
                    lineType:'violet'
                },
                {
                    toCode:262,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:262,
            to:[
                {
                    toCode:261,
                    lineType:'violet'
                },
                {
                    toCode:263,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:263,
            to:[
                {
                    toCode:262,
                    lineType:'violet'
                },
                {
                    toCode:264,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:264,
            to:[
                {
                    toCode:263,
                    lineType:'violet'
                },
                {
                    toCode:265,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:265,
            to:[
                {
                    toCode:264,
                    lineType:'violet'
                },
                {
                    toCode:266,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:266,
            to:[
                {
                    toCode:265,
                    lineType:'violet'
                },
                {
                    toCode:267,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:267,
            to:[
                {
                    toCode:266,
                    lineType:'violet'
                },
                {
                    toCode:268,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:268,
            to:[
                {
                    toCode:267,
                    lineType:'violet'
                },
                {
                    toCode:269,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:269,
            to:[
                {
                    toCode:268,
                    lineType:'violet'
                }
            ]
        },
        {
            fromCode:270,
            to:[
                {
                    toCode:9,
                    lineType:'grey'
                },
                {
                    toCode:271,
                    lineType:'grey'
                }
            ]
        },
        {
            fromCode:271,
            to:[
                {
                    toCode:270,
                    lineType:'grey'
                },
                {
                    toCode:272,
                    lineType:'grey'
                }
            ]
        },
        {
            fromCode:272,
            to:[
                {
                    toCode:271,
                    lineType:'grey'
                }
            ]
        },
        {
            fromCode:273,
            to:[
                {
                    toCode:1,
                    lineType:'orange'
                },
                {
                    toCode:274,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:274,
            to:[
                {
                    toCode:273,
                    lineType:'orange'
                },
                {
                    toCode:275,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:275,
            to:[
                {
                    toCode:274,
                    lineType:'orange'
                },
                {
                    toCode:277,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:276,
            to:[
                {
                    toCode:226,
                    lineType:'pink'
                },
                {
                    toCode:227,
                    lineType:'pink'
                }
            ]
        },
        {
            fromCode:277,
            to:[
                {
                    toCode:275,
                    lineType:'orange'
                },
                {
                    toCode:72,
                    lineType:'orange'
                }
            ]
        },
        {
            fromCode:278,
            to:[
                {
                    toCode:279,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:279,
            to:[
                {
                    toCode:278,
                    lineType:'aqua'
                },
                {
                    toCode:280,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:280,
            to:[
                {
                    toCode:279,
                    lineType:'aqua'
                },
                {
                    toCode:281,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:281,
            to:[
                {
                    toCode:280,
                    lineType:'aqua'
                },
                {
                    toCode:282,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:282,
            to:[
                {
                    toCode:281,
                    lineType:'aqua'
                },
                {
                    toCode:283,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:283,
            to:[
                {
                    toCode:282,
                    lineType:'aqua'
                },
                {
                    toCode:284,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:284,
            to:[
                {
                    toCode:283,
                    lineType:'aqua'
                },
                {
                    toCode:285,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:285,
            to:[
                {
                    toCode:284,
                    lineType:'aqua'
                },
                {
                    toCode:286,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:286,
            to:[
                {
                    toCode:285,
                    lineType:'aqua'
                },
                {
                    toCode:287,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:287,
            to:[
                {
                    toCode:286,
                    lineType:'aqua'
                },
                {
                    toCode:288,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:288,
            to:[
                {
                    toCode:287,
                    lineType:'aqua'
                },
                {
                    toCode:289,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:289,
            to:[
                {
                    toCode:288,
                    lineType:'aqua'
                },
                {
                    toCode:290,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:290,
            to:[
                {
                    toCode:289,
                    lineType:'aqua'
                },
                {
                    toCode:291,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:291,
            to:[
                {
                    toCode:290,
                    lineType:'aqua'
                },
                {
                    toCode:292,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:292,
            to:[
                {
                    toCode:291,
                    lineType:'aqua'
                },
                {
                    toCode:293,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:293,
            to:[
                {
                    toCode:292,
                    lineType:'aqua'
                },{
                    toCode:294,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:294,
            to:[
                {
                    toCode:293,
                    lineType:'aqua'
                },
                {
                    toCode:295,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:295,
            to:[
                {
                    toCode:294,
                    lineType:'aqua'
                },
                {
                    toCode:296,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:296,
            to:[
                {
                    toCode:295,
                    lineType:'aqua'
                },
                {
                    toCode:297,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:297,
            to:[
                {
                    toCode:296,
                    lineType:'aqua'
                },
                {
                    toCode:298,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:298,
            to:[
                {
                    toCode:297,
                    lineType:'aqua'
                }
            ]
        },
        {
            fromCode:299,
            to:[
                {
                    toCode:300,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:300,
            to:[
                {
                    toCode:299,
                    lineType:'rapid'
                },
                {
                    toCode:301,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:301,
            to:[
                {
                    toCode:300,
                    lineType:'rapid'
                },
                {
                    toCode:302,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:302,
            to:[
                {
                    toCode:301,
                    lineType:'rapid'
                },
                {
                    toCode:303,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:303,
            to:[
                {
                    toCode:302,
                    lineType:'rapid'
                },
                {
                    toCode:89,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:304,
            to:[
                {
                    toCode:89,
                    lineType:'rapid'
                },
                {
                    toCode:308,
                    lineType:'rapid'
                },
                {
                    toCode:305,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:305,
            to:[
                {
                    toCode:304,
                    lineType:'rapid'
                },
                {
                    toCode:306,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:306,
            to:[
                {
                    toCode:305,
                    lineType:'rapid'
                },
                {
                    toCode:307,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:307,
            to:[
                {
                    toCode:306,
                    lineType:'rapid'
                },
                {
                    toCode:308,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:308,
            to:[
                {
                    toCode:307,
                    lineType:'rapid'
                },
                {
                    toCode:304,
                    lineType:'rapid'
                }
            ]
        },
        {
            fromCode:309,
            to:[
                {
                    toCode:236,
                    lineType:'pink'
                },
                {
                    toCode:237,
                    lineType:'pink'
                }
            ]
        },


    ]
